package com.company.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.MongoId;

@Document
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class CompanyModel {

    @MongoId
    private String companyId;   // autogenerated id UUID
    private String companyName;
    private String description;
}
